### ISSUE TITLE
[Bug] Could not find expected browser (chrome) locally after `next start`

### ISSUE THREAD

**Issue by snelsi** [neg4n/next-api-og-image#22]
## Environment
```
next-api-og-image: 2.1.1
next: 11.1.2 / 12.0.4
node: 16.13.0
```
MacOS 12.0.1 (M1 Chip)
VS Code

## Bug Description
This package works fine in dev mode when using `next dev`. But if I try to run `next build & next start` I'm getting this error when trying to access the API route:
```
Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (901912).
    at ChromeLauncher.launch (/Users/romanzhuravlov/Documents/GitHub/next-api-og-image/example/node_modules/puppeteer-core/lib/cjs/puppeteer/node/Launcher.js:88:27)
    at async Object.apiResolver (/Users/romanzhuravlov/Documents/GitHub/next-api-og-image/example/node_modules/next/dist/server/api-utils.js:101:9)
    at async Server.handleApiRequest (/Users/romanzhuravlov/Documents/GitHub/next-api-og-image/example/node_modules/next/dist/server/next-server.js:770:9)
    at async Object.fn (/Users/romanzhuravlov/Documents/GitHub/next-api-og-image/example/node_modules/next/dist/server/next-server.js:661:37)
    at async Router.execute (/Users/romanzhuravlov/Documents/GitHub/next-api-og-image/example/node_modules/next/dist/server/router.js:205:32)
    at async Server.run (/Users/romanzhuravlov/Documents/GitHub/next-api-og-image/example/node_modules/next/dist/server/next-server.js:841:29)
    at async Server.handleRequest (/Users/romanzhuravlov/Documents/GitHub/next-api-og-image/example/node_modules/next/dist/server/next-server.js:292:20)
```

Tried both with my own project and examples from the repo `example` folder. 

`npm install` doesn't help:

<img width="1129" alt="Снимок экрана 2021-11-24 в 16 00 45" src="https://user-images.githubusercontent.com/15171036/143252414-7e69b55f-609f-4531-a291-07273bda41e4.png">

**Comment by neg4n** [comment]
Hello, thanks for reporting this 😀 It certainly should not happen. The problem is most likely related to invalid env detection (NODE_ENV). There was similar issue before but i thought I fixed it and as far as I can remember everything was working. It seems that I missed something 

I will take a look on this in my free time 😇 Thanks 👍🏻

**Comment by snelsi** [comment]
@neg4n Hey! Do you have any estimations on when this issue will be resolved? It's a serios blocker, and I'm thinking whether to wait for the fix or try another solution

**Comment by neg4n** [comment]
Hey @snelsi, I suggest u just downgrading `next-api-og-image` to the 2.0.0 version. Regarding the issue fix ETA - I think i will have free time at the weekend to inspect and fix that. Cheers!

**Comment by snelsi** [comment]
Neither version `2.0.0` nor version `1.1.7` works for me  🤔
I'm getting the same "Could not find expected browser (chrome) locally" error

**Comment by neg4n** [comment]
I've just checked and these versions (also the latest one) works for me. I also have the M1 chip 🤔

**Comment by snelsi** [comment]
The following code from [next-og-image](https://github.com/samrobbins85/next-og-image) worked for me.

```tsx
import React from 'react'
import { renderToString } from 'react-dom/server'
import chromium from 'chrome-aws-lambda'

const getContent = () => `<html><body>Hello</body></html>`

const GenerateThumbnail = async (req: NextApiRequest, res: NextApiResponse) => {
  const html = getContent()
  const browser = await chromium.puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath,
    ignoreHTTPSErrors: true,
  })
  const page = await browser.newPage()
  await page.setContent(html)
  await page.setViewport({ width: 1200, height: 630 })
  const imageBuffer = await page.screenshot()
  await browser.close()
  res.setHeader('Content-Type', 'image/jpg')
  res.setHeader('Cache-Control', `public, immutable, no-transform, s-maxage=2592000, max-age=2592000`)
  res.send(imageBuffer)
}

export default GenerateThumbnail
```

**Comment by neg4n** [comment]
Hey @snelsi, I've just inspected the issue and im afraid that the error is on your side 😕 Works flawlessly for me on my local machine + hosted remotely on Vercel

https://test-nextjs-project-ebon.vercel.app/api/ogimage?test=hello

**Comment by snelsi** [comment]
I think you might be overcomplicating things a little bit.

Here's a couple of suggestions:
1) You don't need Puppeteer to send plain html in Dev inspect mode
```tsx
let html =
      htmlTemplate && !reactTemplate
        ? await htmlTemplate({ ...params } as StrategyAwareParams<Strategy, StrategyDetails>)
        : renderToStaticMarkup(
            await reactTemplate({ ...params } as StrategyAwareParams<Strategy, StrategyDetails>),
          )
html =  emojify(html);

// Lauch puppeteer and get a screenshot
if (isProductionLikeMode(envMode) || !inspectHtml) {
    response.setHeader('Content-Type', contentType)
    response.setHeader('Cache-Control', cacheControl)
    response.write(await browserEnvironment.createImage(html))
}
// Send plain html
else {
  response.setHeader('Content-Type', 'text/html')
  response.write(html))
}
```

2) Hardcoding `ChromiumExecutable` is probably not a good idea

3) You can call puppeteer in chrome lambda directly. Swap
```
import core from 'puppeteer-core'
import chrome from 'chrome-aws-lambda'
      
const browser = await core.launch({
  args: chrome.args,
  executablePath: await chrome.executablePath,
  headless: chrome.headless,
})
```

to

```
import chrome from 'chrome-aws-lambda'

// Use chrome.puppeteer directly
const browser = await chrome.puppeteer.launch({
    args: chrome.args,
    defaultViewport: chrome.defaultViewport,
    executablePath: await chrome.executablePath
})
```

4) You can define `isProductionLikeMode` prop once as a global variable instead if calling it as a function every time. Env variables can't change after the build:
```
const isProductionLikeMode = process.env.NODE_ENV !== 'development'
```

**Comment by yashasbhat** [comment]
Hey there @neg4n ! I was trying to use this library to see how it worked, but I'm unfortunately running into a very weird error. I've tried to solve this by searching it up on Google, but to no avail.

Whenever I visit the route `/api/hello` in my browser, I get the following message:

![image](https://user-images.githubusercontent.com/83243777/159299328-e15a5aad-2b27-4182-80ad-a196f5fc007d.png)
___

I downloaded the library as told to from `readme.md` , and copied the code given in the TailwindCSS example section. It looks like:
```js
import { withOGImage } from 'next-api-og-image'

export default withOGImage({
  template: {
    react: ({ myQueryParam }) => `
      <html>
        <head>
          <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
        </head>
        <body>
          <h1 class="flex flex-row text-6xl text-blue-300">${myQueryParam}<span>💻</span></h1>
        </body>
      </html>
    `,
  },
})
```

Is there anything I'm doing wrong? I'm quite new to this, and thought asking this here would help. Thank you, have a good day!

**Comment by yashasbhat** [comment]
Hi @neg4n!

Sorry for the late reply. Just busy with school.

Thank you so much for your response. Installing Google Chrome worked. 

However, I'm not stuck on displaying that value on the frontend, or rather how the image formation would work. Could you please help me understand? I'm sorry if this is a lot to ask, but I'm just quite new to this.

Thanks!

**Comment by snelsi** [comment]
Related:
https://github.com/alixaxel/chrome-aws-lambda/wiki/HOWTO:-Local-Development

If you are facing the same issue, try the following workaround:
```
npm install puppeteer-core chrome-aws-lambda --save-prod
npm install puppeteer --save-dev
```

**Comment by neg4n** [comment]
https://github.com/neg4n/next-api-og-image/releases/tag/4.2.1
