### ISSUE TITLE
Change image resolution / page viewport

### ISSUE THREAD

**Issue by robrechtme** [neg4n/next-api-og-image#25]
Hi :wave:

I just came across this lib, which is just a better implementation of the one I had 😄 
I think it would be useful to have a `width` and `height` option, to specify the image resolution, no? Just an idea!

**Comment by neg4n** [comment]
Hey @robrechtme! Thats a nice idea and thanks for the pull request 🤟🏻 I'll inspect it tomorrow :)

**Comment by neg4n** [comment]
@robrechtme Im sorry, there was just much work to do and I forgot 😄 I'll do it today after work :)
