### ISSUE TITLE
Updates on this library? width and height not working

### ISSUE THREAD

**Issue by gbarkhatov** [neg4n/next-api-og-image#28]
Hey guys, is this library being supported?
width and height still not working on `2.1.1`, even thought it's documented
Also - how can I manipulate the quality of the image? Looks blurred on the dev environment

**Comment by neg4n** [comment]
Hey @gbarkhatov! `next-api-og-image` is under heavy development right now. I'm doing something super cool and soon it will be released here, on this repository. Sorry for not releasing the version with `width` and `height` props on NPM... I have very little amount of free time 🙈

**Comment by neg4n** [comment]
https://github.com/neg4n/next-api-og-image/releases/tag/2.2.0
