### ISSUE TITLE
Add ability to inspect HTML during development

### ISSUE THREAD

**Issue by neg4n** [neg4n/next-api-og-image#3]

**Comment by deadcoder0904** [comment]
Bdw this doesn't do hot module reloading, it only replaces Image with HTML. I meant HMR actually, not this. Hadn't even thought about this as I didn't see the Image part before.

**Comment by deadcoder0904** [comment]
But I'm gonna go the React component way so I don't need it. I think you should also specify the React way as Next.js is used so React is automatically gonna be used. And you get all the benefits like HMR, making dynamic templates by just changing React component, previewing real-time on different posts so helpful in blog, etc....
