### ISSUE TITLE
Suggestion: move chrome-aws-lambda to peer dependency

### ISSUE THREAD

**Issue by transitive-bullshit** [neg4n/next-api-og-image#31]
Since the most recent version of `chrome-aws-lambda` is 49.7 MB, it leaves almost no room for additional client libs in the vercel lambda.

I've been running into this issue and it's really frustrating.

So my proposal is to switch `chrome-aws-lambda` to be a peer dependency and allow the user of this library to choose which chrome version they want to use.

See my other comment here for the savings we're talking about: https://github.com/neg4n/next-api-og-image/issues/23#issuecomment-1090319079

This would require also making `puppeteer-core` a peer dependency, since the two versions need to match up.

**Comment by transitive-bullshit** [comment]
In my case, after a lot of trial & error, I got everything working with `v6.0.0` using resolution overrides as a temporary workaround: https://github.com/transitive-bullshit/nextjs-notion-starter-kit/blob/main/package.json#L72-L75

**Comment by neg4n** [comment]
Thanks @transitive-bullshit for your research regarding this topic 🤟🏻 Your suggestion about switching these `dependencies` to `peerDependencies` seems very sensible to me. I'll investigate the topic as well and apply the changes during this weekend 🚀

**Comment by neg4n** [comment]
https://github.com/neg4n/next-api-og-image/releases/tag/4.0.1

**Comment by transitive-bullshit** [comment]
@neg4n from what I can tell, puppeteer-core and chrome-aws-lambda need to have the same version (or close to the same version); otherwise, the dynamic library lookup fails.

What do you think about making puppeteer-core a peer dep as well?

**Comment by neg4n** [comment]
> @neg4n from what I can tell, puppeteer-core and chrome-aws-lambda need to have the same version (or close to the same version); otherwise, the dynamic library lookup fails.
> 
> What do you think about making puppeteer-core a peer dep as well?

I think thats good idea but it needs further investigation. I've tried to do it when adding changes proposed in this issue but there were some circular deps (?) issues 👀

**Comment by LuighiV** [comment]
Hi, I am trying to use the suggested versions for the packages of `chrome-aws-lambda` but I am getting this error when deploying in vercel:
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'bufferutil' in '/vercel/path0/node_modules/next-api-og-image/node_modules/ws/lib'
```
Do you know how it can be resolved?
