### ISSUE TITLE
Failed to launch the browser process!

### ISSUE THREAD

**Issue by Sumis34** [neg4n/next-api-og-image#35]
I get this error when I start my next app with `yarn dev`

```
error - Error: Failed to launch the browser process! spawn C:\Program Files (x86)\Google\Chrome\Application\chrome.exe ENOENT
```

I have chrome installed on my system but its, not in the path printed in the error. It is in the 64bit folder. `C:\Program Files\Google\Chrome\Application`

**My ENV**
- Node 16.1.0.0
- Next 12.1.0
- chrome-aws-lambda 1.6.3
- Windows

**Comment by linojon** [comment]
same problem here. I used the following steps

* yarn create next-app –typescript
* yarn add next-api-og-image chrome-aws-lambda
* Create github repo and push
* added file pages/api/ogimage/index.js with code pasted from https://github.com/neg4n/next-api-og-image/blob/main/example/pages/api/basic.js 
* Create Vercel app and deploy
* When i visit the url i see the generic Next home page
* When i visit /api/ogimage, 
* Then it fails with 500 error and logs say

```
[GET] /api/ogimage
11:06:35:54
2022-05-23T15:06:40.106Z	6ea5bf36-a40a-4c0a-998e-891d7abd8541	ERROR	Error: Failed to launch the browser process!
/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
    at onClose (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:197:20)
    at Interface.<anonymous> (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:187:68)
    at Interface.emit (node:events:532:35)
    at Interface.close (node:readline:586:8)
    at Socket.onend (node:readline:277:10)
    at Socket.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1346:12)
```

**Comment by Sumis34** [comment]
> same problem here. I used the following steps
> 
> * yarn create next-app –typescript
> * yarn add next-api-og-image chrome-aws-lambda
> * Create github repo and push
> * added file pages/api/ogimage/index.js with code pasted from https://github.com/neg4n/next-api-og-image/blob/main/example/pages/api/basic.js
> * Create Vercel app and deploy
> * When i visit the url i see the generic Next home page
> * When i visit /api/ogimage,
> * Then it fails with 500 error and logs say
> 
> ```
> [GET] /api/ogimage
> 11:06:35:54
> 2022-05-23T15:06:40.106Z	6ea5bf36-a40a-4c0a-998e-891d7abd8541	ERROR	Error: Failed to launch the browser process!
> /tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
> TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
>     at onClose (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:197:20)
>     at Interface.<anonymous> (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:187:68)
>     at Interface.emit (node:events:532:35)
>     at Interface.close (node:readline:586:8)
>     at Socket.onend (node:readline:277:10)
>     at Socket.emit (node:events:532:35)
>     at endReadableNT (node:internal/streams/readable:1346:12)
> ```

@linojon I think your Problem is a different one. If you are using `Node 16.x` on Vercel try version `14.x`. Because not all versions of `chrome-aws-lambda` support version `16`

**Comment by fky2015** [comment]
> I have chrome installed on my system but its, not in the path printed in the error.

It's due to the following code:
https://github.com/neg4n/next-api-og-image/blob/7bdcfa5a12dacfec505833fb797898f2d919777b/src/index.ts#L206-L215

Fortunately, this code only takes effect when in the development environment.

**Comment by neg4n** [comment]
Hey folks! Sorry for late response.

> @linojon I think your Problem is a different one. If you are using `Node 16.x` on Vercel try version `14.x`. Because not all versions of `chrome-aws-lambda` support version `16`

Thanks @Sumis34 for pointing this out. I'll add it to the README.md in section that describes alternative `chrome-aws-lambda` setup 🚀 





> I get this error when I start my next app with `yarn dev`
> 
> ```
> error - Error: Failed to launch the browser process! spawn C:\Program Files (x86)\Google\Chrome\Application\chrome.exe ENOENT
> ```
> 
> I have chrome installed on my system but its, not in the path printed in the error. It is in the 64bit folder. `C:\Program Files\Google\Chrome\Application`
> 
> **My ENV**
> 
> * Node 16.1.0.0
> * Next 12.1.0
> * chrome-aws-lambda 1.6.3
> * Windows

Thanks for reporting this. I'll add support for Windows 64bit path 🤟🏻 

Cheers, Igor

**Comment by neg4n** [comment]
https://github.com/neg4n/next-api-og-image/releases/tag/4.2.1
