### ISSUE TITLE
Failed to launch the browser process

### ISSUE THREAD

**Issue by GeoBrodas** [neg4n/next-api-og-image#39]
![image](https://user-images.githubusercontent.com/68821192/179356539-9d8f5ddc-c81e-4c4e-bab9-c5221a3dc75f.png)
Getting this error

Code Snippet
```js
// ./api/og.js

import { withOGImage } from 'next-api-og-image';

export default withOGImage({
  template: { react: ({ title }) => <h1>{title}</h1> },
  dev: {
    inspectHtml: true,
  },
});
```

Happens when I enter `/api/og?title=Hi`

Running in Brave Browser
I have installed chrome as well but the path is different.

**Comment by neg4n** [comment]
Hey @GeoBrodas! It seems that the issue is resolved since https://github.com/neg4n/next-api-og-image/releases/tag/4.2.1 

Cheers, Igor
