### ISSUE TITLE
Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (901912).

### ISSUE THREAD

**Issue by guhyeon** [neg4n/next-api-og-image#40]
Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (901912).

when build example and start, errors are occurred.
'npm run dev' is ok, but 'npm run build' and 'npm run start' has problem.

reproduce steps

1. clone this project
2. npm install
3. cd example && npm install

after I encountered errors bellow
`It looks like you're trying to use TypeScript but do not have the required package(s) installed.

Please install @types/react by running:`

so i installed @types/react and upgrade next, react
4.   npm install --save-dev @types/react && npm install next@latest && npm upgrade react@latest react-dom@latest 

5. npm build && npm start
6. browser open and go to url http://localhost:3000/api/basic?myQueryParam=asdf

**Comment by kamenskiyyyy** [comment]
I also have this problem, but only on production

**Comment by mvandergrift** [comment]
Same here. Works with dev build, but puppeteer-core cannot find chromium in the production build.

**Comment by neg4n** [comment]
Hey folks @guhyeon @kamenskiyyyy @mvandergrift 

The problem is probably only occurring during production app runtime on the local machine since when `NODE_ENV` is set to `production` and the library tries to load chrome from `chrome-aws-lambda` package instead of retrieving chromium path from the local machine.

I'll try to do something like detecting if the code is run on AWS to solve this

Cheers. Igor

**Comment by kamenskiyyyy** [comment]
@neg4n I found a solution https://github.com/kamenskiyyyy/open-graph-image-example. You just need to remove chrome-aws-lambda.

**Comment by neg4n** [comment]
> @neg4n I found a solution https://github.com/kamenskiyyyy/open-graph-image-example. You just need to remove chrome-aws-lambda.

@kamenskiyyyy 

Im afraid that this can't be solved like this 😔 Only when hosting/running the `next-api-og-image` is done on the machine where you have direct access to the physical resources *(servers, local hosting)* does the problem solve with your solution applied. However, doing so will most likely break library's support for being deployed in the cloud 😭

**Comment by neg4n** [comment]
Hey folks @guhyeon @mvandergrift @kamenskiyyyy 

https://github.com/neg4n/next-api-og-image/releases/tag/4.2.2 🚀 

Thanks for your contributions, feel free to continue the topic if problem still persists 😄

**Comment by wjeliot** [comment]
Serving my Next.js app on DigitalOcean, I'm getting this error after updating to 4.2.2:

`Error: Failed to launch the browser process! spawn /usr/bin/google-chrome ENOENT
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
  at onClose (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:197:20)
  at ChildProcess.<anonymous> (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:189:85)
  at ChildProcess.emit (node:events:513:28)
  at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
  at onErrorNT (node:internal/child_process:478:16)
  at processTicksAndRejections (node:internal/process/task_queues:83:21)`

**Comment by njoguamos** [comment]
> Serving my Next.js app on DigitalOcean, I'm getting this error after updating to 4.2.2:
 Same case with Linode

```
Error: Failed to launch the browser process! spawn /usr/bin/google-chrome ENOENT
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at onErrorNT (node:internal/child_process:476:16)
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.<anonymous> (/home/xxxx/xxxxx/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:189:85)
    at onClose (/home/xxxx/xxxxxxxx/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:197:20)
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
```

I'm still investigating the problem.

**Comment by njoguamos** [comment]
> Serving my Next.js app on DigitalOcean, I'm getting this error after updating to 4.2.2:

@wjeliot [refer to this discussion, it might help ](https://github.com/neg4n/next-api-og-image/discussions/45)
