### ISSUE TITLE
Failed to launch browser process

### ISSUE THREAD

**Issue by schwarzsky** [neg4n/next-api-og-image#41]
My version is already `"next-api-og-image": "^4.2.1"`, in local running fine but in Vercel gives error

```
[GET] /api/ogImage?name=rotterdame&creator=schwarzskra
17:16:38:27
2022-08-07T14:16:42.986ZERROR	Error: Failed to launch the browser process!
/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
```

**Comment by neg4n** [comment]
Hello @schwarzsky! What is your `chrome-aws-lambda` version? When doing research in this topic i remember that versions below `6.0.0` were faulty. Please see https://github.com/neg4n/next-api-og-image#short-note-about-the-peer-dependencies

**Comment by schwarzsky** [comment]
Sorry. 

I have solved according to that comment in a closed issue: https://github.com/neg4n/next-api-og-image/issues/35#issuecomment-1137142166
* Downgrading Vercel NodeJS version from 16.x to 14.x works.

Also, if you still need the version it is `"chrome-aws-lambda": "^6.0.0"`.

**Comment by daveg7lee** [comment]
I got this error again. Because now vercel do not support node 14 and 16
