### ISSUE TITLE
Add option to override default chrome executable and arguments

### ISSUE THREAD

**Issue by vanniewelt** [neg4n/next-api-og-image#44]
I'm trying to use this package in production, but I have an issue with setting up the environment:

```
Error: Failed to launch the browser process!
[0914/172601.987555:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
ROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
```

Sadly, there's no way to specify chrome executable arguments. It would be nice if there was some option for it. It is also not hard to imagine that someone might need to override default executable (for example if someone runs multiple versions of chrome on same machine), so there could be also option for that.

**Comment by neg4n** [comment]
Hey @vanniewelt! Thanks for the suggestion. I think the ability to specify chrome arguments is a must-have for `next-api-og-image`. 

I'll implement it today 🚀

**Comment by njoguamos** [comment]
This would be a great addition.
